#!/usr/bin/env python3
"""
Daily automation for the PHC dashboard.

1. Downloads the current month's Full Month Causelist PDF(s) from the
   PHC website.
2. Parses every downloaded PDF (full content, no date-range filter -
   the site PDF is cumulative for the month, so we always re-parse it
   and dedupe at the record level).
3. Merges the new records into the master cache parquet that app.py
   reads (DEFAULT_PARQUET_PATH in app.py), using the SAME _prepare()
   logic as data_loader.py so dtypes/columns stay identical.

Run manually:   python scripts/scrape_and_update.py
Run in CI:      see .github/workflows/daily_update.yml
"""
import os
import re
import sys
import logging
from pathlib import Path
from datetime import datetime

import requests
import pandas as pd
import pdfplumber
from bs4 import BeautifulSoup
from urllib.parse import urljoin

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
from data_loader import _prepare  # noqa: E402

# ----------------------- CONFIG -----------------------
BASE_URL = "https://www.peshawarhighcourt.gov.pk"
PAGE_URL = f"{BASE_URL}/app/site/5/p/Full_Month_Causelist.html"
HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}

DOWNLOAD_DIR = REPO_ROOT / "downloads" / "causelists"
MASTER_PARQUET = REPO_ROOT / "cause_lists_combined_2017_Jan_to_2026_July_MASTER.cache.parquet"
ERROR_LOG = REPO_ROOT / "phc_parser_errors.log"

LINE_CLUSTER_TOLERANCE = 4
LEFT_BOUND_DEFAULT = 190
RIGHT_BOUND_DEFAULT = 400

logging.basicConfig(
    filename=str(ERROR_LOG),
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)
_root_logger = logging.getLogger()
if not any(getattr(h, "_phc_console", False) for h in _root_logger.handlers):
    console = logging.StreamHandler(sys.stdout)
    console.setLevel(logging.INFO)
    console._phc_console = True
    _root_logger.addHandler(console)
log = logging.getLogger("phc_daily")

# ----------------------- REGEX -----------------------
SECTION_RE = re.compile(r'^[A-Z][A-Z\s\(\)\-]*\bCASES?\b$')
COURT_RE = re.compile(r'court\s*no\.?\s*:?\s*(\d+)', re.IGNORECASE)
FOOTER_RE = re.compile(
    r'IT BRANCH|COMPUTER (BRANCH|SECTION)|MIS BRANCH|REPORT GENERATED BY|'
    r'PESHAWAR HIGH COURT,?\s*PESHAWAR$', re.IGNORECASE
)
PAGE_NO_RE = re.compile(r'^_+\s*\d+\s*_+$')
NOISE_RE = re.compile(r'^BEFORE:-|VIDEO LINK', re.IGNORECASE)
JUDGE_LINE_RE = re.compile(r'MRS?\.?\s*JUSTICE', re.IGNORECASE)
DELETED_CASES_RE = re.compile(r'\bDELETED\s+CASES\b', re.IGNORECASE)
JUDGE_NAME_EXTRACT_RE = re.compile(
    r'(MRS?\.?\s*JUSTICE\s+[A-Z][A-Za-z,\.\s]*?)(?=\s*&\s*$|\s*BEFORE:-|\s*$)', re.IGNORECASE
)
DATE_RE = re.compile(r'DAILY LIST FOR\s+(\w+),\s*(\d{1,2})\s+(\w+),\s*(\d{4})', re.IGNORECASE)
VS_RE = re.compile(r'\bV\s*[/.]?\s*S\b|\bVERSUS\b', re.IGNORECASE)
SR_START_RE = re.compile(r'^(\d+)\.?\s*$|^(\d+)\.?\s|^\.\s*$|^\.\s')
DATE_BY_COURT_RE = re.compile(r'\(\s*Date\s+By\s+Court\s*\)', re.IGNORECASE)
CASE_NO_RE = re.compile(
    r'^(?P<type>[A-Za-z][A-Za-z.\- ]{0,10}?)\s*[.\s]*'
    r'(?P<number>[0-9]+[A-Za-z\-]*)\s*/\s*(?P<year>\d{4})'
)

CSV_FIELDS = [
    'Source_File', 'Page', 'Day', 'Date', 'Month', 'Year',
    'Court_No', 'Judges', 'Case_Category', 'Section',
    'Sr_No', 'Case_No', 'System_ID',
    'Case_Title', 'Petitioner_Advocate', 'Respondent_Advocates',
    'Needs_Review',
]


# ----------------------- SCRAPER -----------------------
def get_pdf_links():
    now = datetime.now()
    form_data = {
        "year": str(now.year),
        "month": f"{now.month:02d}",
        "btnSearch": "Search Causelist",
    }
    resp = requests.post(PAGE_URL, headers=HEADERS, data=form_data, timeout=30)
    resp.raise_for_status()
    soup = BeautifulSoup(resp.text, "html.parser")
    links = []
    for a in soup.find_all("a", href=True):
        href = a["href"]
        if href.lower().endswith(".pdf") or "/causeLists/" in href:
            links.append(urljoin(BASE_URL, href))
    return links


def download_pdfs(links):
    DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)
    downloaded = []
    for url in links:
        try:
            r = requests.get(url, headers=HEADERS, timeout=60)
            r.raise_for_status()
            fname = DOWNLOAD_DIR / os.path.basename(url.split("?")[0])
            fname.write_bytes(r.content)
            downloaded.append(fname)
            print(f"[+] Downloaded: {fname.name}")
        except Exception as e:
            log.error(f"Failed to download {url}: {e}")
    return downloaded


# ----------------------- LINE / COLUMN RECONSTRUCTION -----------------------
def cluster_words_into_lines(words):
    if not words:
        return []
    ws = sorted(words, key=lambda w: (w['top'], w['x0']))
    lines = []
    current = [ws[0]]
    current_top = ws[0]['top']
    for w in ws[1:]:
        if abs(w['top'] - current_top) <= LINE_CLUSTER_TOLERANCE:
            current.append(w)
        else:
            lines.append(current)
            current = [w]
            current_top = w['top']
        current_top = sum(x['top'] for x in current) / len(current)
    lines.append(current)
    for line in lines:
        line.sort(key=lambda w: w['x0'])
    return lines


def detect_column_bounds(all_words):
    xs = sorted(set(round(w['x0'], 1) for w in all_words))
    if len(xs) < 3:
        return LEFT_BOUND_DEFAULT, RIGHT_BOUND_DEFAULT
    gaps = [(xs[i + 1] - xs[i], (xs[i] + xs[i + 1]) / 2) for i in range(len(xs) - 1)]
    candidates = [g for g in gaps if g[0] >= 15 and 80 <= g[1] <= 480]
    candidates.sort(key=lambda g: g[1])
    if len(candidates) >= 2:
        early = [g for g in candidates if g[1] < 300]
        late = [g for g in candidates if g[1] >= 300]
        left_bound = max(early, key=lambda g: g[0])[1] if early else LEFT_BOUND_DEFAULT
        right_bound = max(late, key=lambda g: g[0])[1] if late else RIGHT_BOUND_DEFAULT
        if left_bound < right_bound:
            return left_bound, right_bound
    return LEFT_BOUND_DEFAULT, RIGHT_BOUND_DEFAULT


def line_to_text(line_words):
    return ' '.join(w['text'] for w in line_words).strip()


def bucket_line(line_words, left_bound, right_bound):
    left = [w for w in line_words if w['x0'] < left_bound]
    mid = [w for w in line_words if left_bound <= w['x0'] < right_bound]
    right = [w for w in line_words if w['x0'] >= right_bound]
    return line_to_text(left), line_to_text(mid), line_to_text(right)


def parse_case_number(raw: str):
    raw = raw.strip()
    m = CASE_NO_RE.match(raw)
    if not m:
        return '', '', '', raw
    case_type = m.group('type').strip(' .')
    case_number = m.group('number').strip()
    case_year = m.group('year').strip()
    remainder = raw[m.end():].strip()
    return case_type, case_number, case_year, remainder


def classify_and_filter_lines(raw_lines, doc_state):
    data_lines = []
    active = doc_state.get('ever_active', False)
    court_no = doc_state.get('court_no', '')
    judge_buffer = []

    for lw in raw_lines:
        full = line_to_text(lw)

        if DELETED_CASES_RE.search(full):
            doc_state['judges'] = 'N/A (Deleted Cases List - no judge listed)'
            judge_buffer = []

        dm = DATE_RE.search(full)
        if dm:
            doc_state['day'] = dm.group(1)
            doc_state['date'] = dm.group(2)
            doc_state['month'] = dm.group(3)
            doc_state['year'] = dm.group(4)
            continue

        cm = COURT_RE.search(full)
        if cm:
            court_no = cm.group(1)
            doc_state['court_no'] = court_no
            active = True
            doc_state['ever_active'] = True
            continue

        if JUDGE_LINE_RE.search(full):
            m = JUDGE_NAME_EXTRACT_RE.search(full)
            if m:
                name = m.group(1).strip(' &').strip()
                name = re.sub(r'\s+', ' ', name)
                if name and name not in judge_buffer:
                    judge_buffer.append(name)
            continue

        if not active:
            continue

        if SECTION_RE.match(full.strip()):
            if judge_buffer:
                doc_state['judges'] = ' & '.join(judge_buffer)
                judge_buffer = []

        if PAGE_NO_RE.match(full) or FOOTER_RE.search(full) or NOISE_RE.search(full):
            continue

        data_lines.append(lw)

    if judge_buffer:
        doc_state['judges'] = ' & '.join(judge_buffer)

    return data_lines, court_no


def build_record(block, section, court_no, sr_no, doc_state, source_file, page_no, global_sr_holder):
    lefts = [b[0] for b in block if b[0]]
    mids_all = [b[1] for b in block]
    rights_all = [b[2] for b in block]

    left_no_sr = SR_START_RE.sub('', lefts[0], count=1).strip() if lefts else ''
    full_left = ' '.join([left_no_sr] + lefts[1:]).strip()
    sys_ids = re.findall(r'\((\d{5,})\)', full_left)
    sys_id = sys_ids[-1] if sys_ids else ''
    case_type, case_number, case_year, extra_note = parse_case_number(full_left)
    extra_note = re.sub(r'\(\d{5,}\)', '', extra_note).strip()

    if case_type and case_number and case_year:
        case_no = f"{case_type} {case_number}/{case_year}"
        if extra_note:
            case_no = f"{case_no} {extra_note}"
    else:
        case_no = full_left

    sep_idx = None
    for idx, m in enumerate(mids_all):
        if m and VS_RE.search(m):
            sep_idx = idx
            break

    def clean(txt):
        return DATE_BY_COURT_RE.sub('', txt).strip()

    if sep_idx is not None:
        petitioner = ' '.join(clean(m) for m in mids_all[:sep_idx] if clean(m)).strip()
        respondent = ' '.join(clean(m) for m in mids_all[sep_idx + 1:] if clean(m)).strip()
        pet_adv = ' '.join(r for r in rights_all[:sep_idx] if r).strip()
        res_adv = ' '.join(r for r in rights_all[sep_idx + 1:] if r).strip()
    else:
        all_mid = ' '.join(clean(m) for m in mids_all if clean(m)).strip()
        petitioner = all_mid
        respondent = ''
        pet_adv = ' '.join(r for r in rights_all if r).strip()
        res_adv = ''

    if petitioner and respondent:
        case_title = f"{petitioner} Vs {respondent}"
    else:
        case_title = petitioner or respondent

    case_cat = (
        'Notice Case'
        if any(x in section.upper() for x in ('NOTICE', 'DETENTION', 'PRE-ADMISSION'))
        else 'Motion Case'
    )

    needs_review = (
        sep_idx is None or not case_no or not petitioner
        or not respondent or not pet_adv
    )

    global_sr_holder[0] += 1
    print(f"\r  {source_file} p{page_no} | Court {court_no} | Rec {global_sr_holder[0]} | "
          f"{case_no[:30]}          ", end='', flush=True)

    return {
        'Source_File': source_file, 'Page': page_no,
        'Day': doc_state.get('day', ''), 'Date': doc_state.get('date', ''),
        'Month': doc_state.get('month', ''), 'Year': doc_state.get('year', ''),
        'Court_No': court_no, 'Judges': doc_state.get('judges', ''),
        'Case_Category': case_cat, 'Section': section,
        'Sr_No': sr_no, 'Case_No': case_no, 'System_ID': sys_id,
        'Case_Title': case_title, 'Petitioner_Advocate': pet_adv,
        'Respondent_Advocates': res_adv,
        'Needs_Review': 'Yes' if needs_review else 'No',
    }


def parse_page(page, page_no, source_file, doc_state, global_sr_holder):
    words = page.extract_words(use_text_flow=False, keep_blank_chars=False)
    if not words:
        return []
    raw_lines = cluster_words_into_lines(words)
    data_lines, court_no = classify_and_filter_lines(raw_lines, doc_state)
    if not data_lines:
        return []
    data_words = [w for lw in data_lines for w in lw]
    left_bound, right_bound = detect_column_bounds(data_words)

    lines = []
    for lw in data_lines:
        left, mid, right = bucket_line(lw, left_bound, right_bound)
        lines.append((left, mid, right))

    section = ''
    records = []
    i, n = 0, len(lines)
    while i < n:
        left, mid, right = lines[i]
        if not left and not right and SECTION_RE.match(mid.strip()):
            section = mid.strip()
            i += 1
            continue
        sm = SR_START_RE.match(left)
        if sm and left:
            sr_no = sm.group(1) or sm.group(2) or ''
            block = [(left, mid, right)]
            j = i + 1
            while j < n:
                l2, m2, r2 = lines[j]
                if not l2 and not r2 and SECTION_RE.match(m2.strip()):
                    break
                if SR_START_RE.match(l2) and l2:
                    break
                block.append((l2, m2, r2))
                j += 1
            i = j
            records.append(build_record(block, section, court_no, sr_no, doc_state,
                                         source_file, page_no, global_sr_holder))
        else:
            i += 1
    return records


def process_pdf(pdf_path: Path, global_sr_holder):
    source_label = pdf_path.name
    all_records = []
    doc_state = {}
    with pdfplumber.open(str(pdf_path)) as pdf:
        for page_no, page in enumerate(pdf.pages, start=1):
            try:
                records = parse_page(page, page_no, source_label, doc_state, global_sr_holder)
                all_records.extend(records)
            except Exception as e:
                log.error(f"{source_label} page {page_no}: FAILED ({e}). Skipping page.")
    return all_records


# ----------------------- MAIN -----------------------
def main():
    print("Checking PHC website for current month causelist PDF(s)...")
    links = get_pdf_links()
    if not links:
        print("[!] No PDF links found on the page — site structure may have changed.")
        return

    pdfs = download_pdfs(links)
    if not pdfs:
        print("No PDFs downloaded. Nothing to update.")
        return

    global_sr_holder = [0]
    all_new_records = []
    for pdf_path in pdfs:
        print(f"\nParsing {pdf_path.name} ...")
        recs = process_pdf(pdf_path, global_sr_holder)
        print(f"\n  -> {len(recs)} records")
        all_new_records.extend(recs)

    if not all_new_records:
        print("No records parsed from downloaded PDFs.")
        return

    new_df = pd.DataFrame(all_new_records, columns=CSV_FIELDS).astype(str)
    for col in new_df.columns:
        new_df[col] = new_df[col].fillna("")
    new_prepared = _prepare(new_df)

    if MASTER_PARQUET.exists():
        old_df = pd.read_parquet(MASTER_PARQUET)
        combined = pd.concat([old_df, new_prepared], ignore_index=True)
    else:
        combined = new_prepared

    dedupe_cols = [c for c in ["Hearing_Date", "Court_No", "Sr_No", "Case_No"] if c in combined.columns]
    before = len(combined)
    if dedupe_cols:
        combined = combined.drop_duplicates(subset=dedupe_cols, keep="last").reset_index(drop=True)
    after_dedup = len(combined)

    # Keep only the last few years' worth of data in the master parquet.
    # Update KEEP_YEARS below if the retention window ever needs to change.
    KEEP_YEARS = {2024, 2025, 2026}
    combined = combined[combined["Hearing_Date"].dt.year.isin(KEEP_YEARS)].reset_index(drop=True)
    for col in combined.select_dtypes(include="category").columns:
        combined[col] = combined[col].cat.remove_unused_categories()

    MASTER_PARQUET.parent.mkdir(parents=True, exist_ok=True)
    combined.to_parquet(MASTER_PARQUET)
    print(f"\nMerged {len(new_prepared)} parsed record(s), dropped {before - after_dedup} duplicate(s), "
          f"trimmed {after_dedup - len(combined)} row(s) outside {sorted(KEEP_YEARS)}. "
          f"Master parquet now has {len(combined)} rows -> {MASTER_PARQUET.name}")


if __name__ == "__main__":
    main()
