"""
Standalone scraper for the 4 additional PHC benches — Abbottabad, D.I.Khan,
Mingora, Bannu. Fully self-contained: no dependency on the PHC-Dasboard
repo's data_loader.py or scrape_and_update.py.

Run anywhere:
    pip install requests pandas pdfplumber beautifulsoup4 pyarrow
    python scrape_benches.py

Output: phc_benches_combined.parquet (written in the same folder as this
script). Merge this into your main dashboard however you like later.
"""
import os
import re
import sys
import logging
from pathlib import Path
from datetime import date, timedelta

import requests
import pandas as pd
import pdfplumber
from bs4 import BeautifulSoup
from urllib.parse import urljoin

# ----------------------- CONFIG -----------------------
BASE_URL = "https://www.peshawarhighcourt.gov.pk"
BENCH_URL = f"{BASE_URL}/app/site/4/p/Causelists_List.html"
HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}

SCRIPT_DIR = Path(__file__).resolve().parent
DOWNLOAD_DIR = SCRIPT_DIR / "downloads" / "bench_causelists"
OUTPUT_PARQUET = SCRIPT_DIR / "phc_benches_combined.parquet"
ERROR_LOG = SCRIPT_DIR / "bench_parser_errors.log"

SITES = {
    "Abbottabad": {
        "api_url": "https://www.peshawarhcatd.gov.pk/APIS/get_datewise_causelists.php",
        "type": "json_api",
    },
    "Mingora": {
        "form_url": "https://peshawarhcmb.gov.pk/mod/mod_public/pages/ajaxPhp/calendar_causelist.php",
        "type": "date_form",
        "format": "html_table",
        "lookback_days": 3,
    },
    "Bannu": {
        "api_url": "https://peshawarhcbannubench.gov.pk/APIS/get_datewise_causelists.php",
        "type": "json_api",
    },
    "D.I.Khan": {
        "search_url": "https://diary.peshawarhcdikbench.gov.pk/APIS/search_cases_result.php",
        "type": "case_registry",
        "caseyear": "2026",
        "casenamecode": "7",  # only confirmed code (Cr.A) — add more codes if the site has other case types
    },
    # "D.I.Khan": no causelist PDFs on diary.peshawarhcdikbench.gov.pk (case-diary system only) — skipped
    # "Bannu": TODO — need page structure from peshawarhcbannubench.gov.pk
}


def get_date_form_pdf_links(form_url, session, lookback_days=3):
    links = []
    end_date = date.today()
    start_date = end_date - timedelta(days=lookback_days)
    d = start_date
    while d <= end_date:
        date_str = d.isoformat()
        try:
            resp = session.post(form_url, data={"dated": date_str}, headers=HEADERS, timeout=30)
            resp.raise_for_status()
            soup = BeautifulSoup(resp.text, "html.parser")
            for a in soup.find_all("a", class_="btn-success", href=True):
                links.append(a["href"])
        except Exception as e:
            print(f"    [debug] {form_url} dated={date_str}: fetch failed ({e})")
        d += timedelta(days=1)
    return links


def get_json_api_pdf_links(api_url, session, max_pages=5):
    links = []
    page = 1
    while page <= max_pages:
        resp = session.get(api_url, params={"page": page, "limit": 10}, headers=HEADERS, timeout=30)
        resp.raise_for_status()
        payload = resp.json()
        data = payload.get("data", [])
        if not data:
            break
        for item in data:
            path = item.get("path")
            if path:
                links.append(path)
        total = payload.get("total", 0)
        if page * payload.get("limit", 10) >= total:
            break
        page += 1
    return links


LINE_CLUSTER_TOLERANCE = 4
LEFT_BOUND_DEFAULT = 190
RIGHT_BOUND_DEFAULT = 400

logging.basicConfig(
    filename=str(ERROR_LOG),
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)
_root_logger = logging.getLogger()
if not any(getattr(h, "_bench_console", False) for h in _root_logger.handlers):
    console = logging.StreamHandler(sys.stdout)
    console.setLevel(logging.INFO)
    console._bench_console = True
    _root_logger.addHandler(console)
log = logging.getLogger("phc_bench_daily")

# ----------------------- REGEX (same patterns as main PHC parser) -----------------------
SECTION_RE = re.compile(r'^[A-Z][A-Z\s\(\)\-]*\bCASES?\b$')
COURT_RE = re.compile(r'court\s*no\.?\s*:?\s*(\d+)', re.IGNORECASE)
FOOTER_RE = re.compile(
    r'IT BRANCH|COMPUTER (BRANCH|SECTION)|MIS BRANCH|REPORT GENERATED BY|'
    r'PESHAWAR HIGH COURT,?\s*PESHAWAR$', re.IGNORECASE
)
PAGE_NO_RE = re.compile(r'^_+\s*\d+\s*_+$')
NOISE_RE = re.compile(r'^BEFORE:-|VIDEO LINK', re.IGNORECASE)
JUDGE_LINE_RE = re.compile(r'MRS?\.?\s*JUSTICE', re.IGNORECASE)
DELETED_CASES_RE = re.compile(r'\bDELETED\s+CASES\b', re.IGNORECASE)
JUDGE_NAME_EXTRACT_RE = re.compile(
    r'(MRS?\.?\s*JUSTICE\s+[A-Z][A-Za-z,\.\s]*?)(?=\s*&\s*$|\s*BEFORE:-|\s*$)', re.IGNORECASE
)
DATE_RE = re.compile(r'DAILY LIST FOR\s+(\w+),\s*(\d{1,2})\s+(\w+),\s*(\d{4})', re.IGNORECASE)
VS_RE = re.compile(r'\bV\s*[/.]?\s*S\b|\bVERSUS\b', re.IGNORECASE)
SR_START_RE = re.compile(r'^(\d+)\.?\s*$|^(\d+)\.?\s|^\.\s*$|^\.\s')
DATE_BY_COURT_RE = re.compile(r'\(\s*Date\s+By\s+Court\s*\)', re.IGNORECASE)
CASE_NO_RE = re.compile(
    r'^(?P<type>[A-Za-z][A-Za-z.\- ]{0,10}?)\s*[.\s]*'
    r'(?P<number>[0-9]+[A-Za-z\-]*)\s*/\s*(?P<year>\d{4})'
)

# ----------------------- MINGORA HTML TABLE PARSER -----------------------
def parse_mingora_html(html_text, source_url, bench_name, global_sr_holder):
    soup = BeautifulSoup(html_text, "html.parser")
    records = []

    # judge name — the grid div right after the label "Before"
    judge = ""
    for div in soup.find_all("div", style=True):
        if "grid-template-columns" in div.get("style", ""):
            cells = div.find_all("div")
            if len(cells) >= 2 and "Before" in cells[0].get_text(strip=True):
                judge = cells[1].get_text(strip=True)
            break

    # date/title
    h3 = soup.find("h3")
    title_text = h3.get_text(" ", strip=True) if h3 else ""

    current_section = ""
    for tr in soup.find_all("tr"):
        section_div = tr.find("div", style=lambda s: s and "text-decoration: underline" in s)
        if section_div:
            current_section = section_div.get_text(strip=True)
            continue

        tds = tr.find_all("td", recursive=False)
        if len(tds) < 4:
            continue

        sr_no = tds[0].get_text(strip=True)
        if not sr_no or not sr_no[0].isdigit():
            continue

        case_cell = tds[1]
        case_no_tag = case_cell.find("strong", class_="case-number")
        case_no = case_no_tag.get_text(strip=True) if case_no_tag else case_cell.get_text(" ", strip=True)

        petitioner_cell = tds[2] if len(tds) > 2 else None
        pet_tag = petitioner_cell.find("strong", class_="case-number") if petitioner_cell else None
        petitioner = pet_tag.get_text(strip=True) if pet_tag else ""
        pet_advocate = ""
        if petitioner_cell:
            adv_divs = petitioner_cell.find_all("div")
            pet_advocate = " ".join(d.get_text(strip=True) for d in adv_divs if d.get_text(strip=True))

        respondent_cell = tds[4] if len(tds) > 4 else None
        res_tag = respondent_cell.find("strong", class_="case-number") if respondent_cell else None
        respondent = res_tag.get_text(strip=True) if res_tag else ""
        res_advocate = ""
        if respondent_cell:
            spans = respondent_cell.find_all("span")
            res_advocate = " ".join(s.get_text(strip=True) for s in spans if s.get_text(strip=True))

        case_title = f"{petitioner} Vs {respondent}" if petitioner and respondent else (petitioner or respondent)
        case_cat = "Notice Case" if "NOTICE" in current_section.upper() else "Motion Case"

        global_sr_holder[0] += 1
        records.append({
            "Source_File": source_url, "Page": 1, "Bench": bench_name,
            "Day": "", "Date": "", "Month": "", "Year": "",
            "Court_No": "", "Judges": judge,
            "Case_Category": case_cat, "Section": current_section,
            "Sr_No": sr_no, "Case_No": case_no, "System_ID": "",
            "Case_Title": case_title, "Petitioner_Advocate": pet_advocate,
            "Respondent_Advocates": res_advocate,
            "Needs_Review": "No" if (petitioner and respondent and case_no) else "Yes",
        })

    return records


def get_case_registry_records(search_url, session, caseyear, casenamecode, global_sr_holder):
    payload = {
        "casetitle": "",
        "caseno": "",
        "caseyear": caseyear,
        "casenamecode": casenamecode,
    }
    resp = session.post(search_url, data=payload, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    result = resp.json()
    rows = result.get("data", [])

    records = []
    for row in rows:
        global_sr_holder[0] += 1
        petitioner = (row.get("PARTY") or "").strip()
        respondent = (row.get("PARTY1") or "").strip()
        case_title = f"{petitioner} Vs {respondent}" if petitioner and respondent else (petitioner or respondent)
        case_type_label = (row.get("CASECODEDTL") or "").split("@")[-1] if row.get("CASECODEDTL") else ""
        case_no = f"{case_type_label} {row.get('CASENO', '')}/{row.get('CASEYEAR', '')}".strip()
        disposed = bool(row.get("DISPOSALDATE"))

        records.append({
            "Source_File": search_url, "Page": 1, "Bench": "D.I.Khan",
            "Day": "", "Date": row.get("INSTITUTIONDATE", "") or "",
            "Month": "", "Year": row.get("CASEYEAR", "") or "",
            "Court_No": row.get("BENCH", "") or "", "Judges": "",
            "Case_Category": "Disposed" if disposed else "Pending", "Section": row.get("COMMENTS", "") or "",
            "Sr_No": str(global_sr_holder[0]), "Case_No": case_no, "System_ID": row.get("CASECODE", "") or "",
            "Case_Title": case_title, "Petitioner_Advocate": "", "Respondent_Advocates": "",
            "Needs_Review": "No" if (petitioner and respondent) else "Yes",
        })
    return records


FIELDS = [
    'Source_File', 'Page', 'Bench', 'Day', 'Date', 'Month', 'Year',
    'Court_No', 'Judges', 'Case_Category', 'Section',
    'Sr_No', 'Case_No', 'System_ID',
    'Case_Title', 'Petitioner_Advocate', 'Respondent_Advocates',
    'Needs_Review',
]


# ----------------------- BENCH PAGE FETCH -----------------------
def download_pdf(url, bench_name):
    bench_dir = DOWNLOAD_DIR / bench_name.replace(".", "").replace(" ", "_")
    bench_dir.mkdir(parents=True, exist_ok=True)

    last_seg = url.split("/")[-1].split("?")[0]
    if last_seg.lower().endswith(".pdf") and len(last_seg) < 100:
        fname = bench_dir / last_seg
    else:
        import hashlib
        url_hash = hashlib.md5(url.encode()).hexdigest()[:12]
        fname = bench_dir / f"causelist_{url_hash}.pdf"

    if fname.exists() and fname.stat().st_size > 0:
        return fname

    dl_headers = dict(HEADERS)
    dl_headers["Referer"] = url.split("/")[0] + "//" + url.split("/")[2] + "/"
    r = requests.get(url, headers=dl_headers, timeout=60, allow_redirects=True)
    r.raise_for_status()
    content_type = r.headers.get("Content-Type", "")
    if not r.content.startswith(b"%PDF"):
        print(f"    [debug] {url} did NOT return a PDF. Content-Type={content_type}, "
              f"first 200 bytes: {r.content[:200]!r}")
    fname.write_bytes(r.content)
    print(f"[+] Downloaded: {fname}")
    return fname


# ----------------------- LINE / COLUMN RECONSTRUCTION -----------------------
def cluster_words_into_lines(words):
    if not words:
        return []
    ws = sorted(words, key=lambda w: (w['top'], w['x0']))
    lines = []
    current = [ws[0]]
    current_top = ws[0]['top']
    for w in ws[1:]:
        if abs(w['top'] - current_top) <= LINE_CLUSTER_TOLERANCE:
            current.append(w)
        else:
            lines.append(current)
            current = [w]
            current_top = w['top']
        current_top = sum(x['top'] for x in current) / len(current)
    lines.append(current)
    for line in lines:
        line.sort(key=lambda w: w['x0'])
    return lines


def detect_column_bounds(all_words):
    xs = sorted(set(round(w['x0'], 1) for w in all_words))
    if len(xs) < 3:
        return LEFT_BOUND_DEFAULT, RIGHT_BOUND_DEFAULT
    gaps = [(xs[i + 1] - xs[i], (xs[i] + xs[i + 1]) / 2) for i in range(len(xs) - 1)]
    candidates = [g for g in gaps if g[0] >= 15 and 80 <= g[1] <= 480]
    candidates.sort(key=lambda g: g[1])
    if len(candidates) >= 2:
        early = [g for g in candidates if g[1] < 300]
        late = [g for g in candidates if g[1] >= 300]
        left_bound = max(early, key=lambda g: g[0])[1] if early else LEFT_BOUND_DEFAULT
        right_bound = max(late, key=lambda g: g[0])[1] if late else RIGHT_BOUND_DEFAULT
        if left_bound < right_bound:
            return left_bound, right_bound
    return LEFT_BOUND_DEFAULT, RIGHT_BOUND_DEFAULT


def line_to_text(line_words):
    return ' '.join(w['text'] for w in line_words).strip()


def bucket_line(line_words, left_bound, right_bound):
    left = [w for w in line_words if w['x0'] < left_bound]
    mid = [w for w in line_words if left_bound <= w['x0'] < right_bound]
    right = [w for w in line_words if w['x0'] >= right_bound]
    return line_to_text(left), line_to_text(mid), line_to_text(right)


def parse_case_number(raw: str):
    raw = raw.strip()
    m = CASE_NO_RE.match(raw)
    if not m:
        return '', '', '', raw
    case_type = m.group('type').strip(' .')
    case_number = m.group('number').strip()
    case_year = m.group('year').strip()
    remainder = raw[m.end():].strip()
    return case_type, case_number, case_year, remainder


def classify_and_filter_lines(raw_lines, doc_state):
    data_lines = []
    active = doc_state.get('ever_active', False)
    court_no = doc_state.get('court_no', '')
    judge_buffer = []

    for lw in raw_lines:
        full = line_to_text(lw)

        if DELETED_CASES_RE.search(full):
            doc_state['judges'] = 'N/A (Deleted Cases List - no judge listed)'
            judge_buffer = []

        dm = DATE_RE.search(full)
        if dm:
            doc_state['day'] = dm.group(1)
            doc_state['date'] = dm.group(2)
            doc_state['month'] = dm.group(3)
            doc_state['year'] = dm.group(4)
            continue

        cm = COURT_RE.search(full)
        if cm:
            court_no = cm.group(1)
            doc_state['court_no'] = court_no
            active = True
            doc_state['ever_active'] = True
            continue

        if JUDGE_LINE_RE.search(full):
            m = JUDGE_NAME_EXTRACT_RE.search(full)
            if m:
                name = m.group(1).strip(' &').strip()
                name = re.sub(r'\s+', ' ', name)
                if name and name not in judge_buffer:
                    judge_buffer.append(name)
            continue

        if not active:
            continue

        if SECTION_RE.match(full.strip()):
            if judge_buffer:
                doc_state['judges'] = ' & '.join(judge_buffer)
                judge_buffer = []

        if PAGE_NO_RE.match(full) or FOOTER_RE.search(full) or NOISE_RE.search(full):
            continue

        data_lines.append(lw)

    if judge_buffer:
        doc_state['judges'] = ' & '.join(judge_buffer)

    return data_lines, court_no


def build_record(block, section, court_no, sr_no, doc_state, source_file, page_no, bench_name, global_sr_holder):
    lefts = [b[0] for b in block if b[0]]
    mids_all = [b[1] for b in block]
    rights_all = [b[2] for b in block]

    left_no_sr = SR_START_RE.sub('', lefts[0], count=1).strip() if lefts else ''
    full_left = ' '.join([left_no_sr] + lefts[1:]).strip()
    sys_ids = re.findall(r'\((\d{5,})\)', full_left)
    sys_id = sys_ids[-1] if sys_ids else ''
    case_type, case_number, case_year, extra_note = parse_case_number(full_left)
    extra_note = re.sub(r'\(\d{5,}\)', '', extra_note).strip()

    if case_type and case_number and case_year:
        case_no = f"{case_type} {case_number}/{case_year}"
        if extra_note:
            case_no = f"{case_no} {extra_note}"
    else:
        case_no = full_left

    sep_idx = None
    for idx, m in enumerate(mids_all):
        if m and VS_RE.search(m):
            sep_idx = idx
            break

    def clean(txt):
        return DATE_BY_COURT_RE.sub('', txt).strip()

    if sep_idx is not None:
        petitioner = ' '.join(clean(m) for m in mids_all[:sep_idx] if clean(m)).strip()
        respondent = ' '.join(clean(m) for m in mids_all[sep_idx + 1:] if clean(m)).strip()
        pet_adv = ' '.join(r for r in rights_all[:sep_idx] if r).strip()
        res_adv = ' '.join(r for r in rights_all[sep_idx + 1:] if r).strip()
    else:
        all_mid = ' '.join(clean(m) for m in mids_all if clean(m)).strip()
        petitioner = all_mid
        respondent = ''
        pet_adv = ' '.join(r for r in rights_all if r).strip()
        res_adv = ''

    if petitioner and respondent:
        case_title = f"{petitioner} Vs {respondent}"
    else:
        case_title = petitioner or respondent

    case_cat = (
        'Notice Case'
        if any(x in section.upper() for x in ('NOTICE', 'DETENTION', 'PRE-ADMISSION'))
        else 'Motion Case'
    )

    needs_review = (
        sep_idx is None or not case_no or not petitioner
        or not respondent or not pet_adv
    )

    global_sr_holder[0] += 1
    print(f"\r  [{bench_name}] {source_file} p{page_no} | Court {court_no} | Rec {global_sr_holder[0]} | "
          f"{case_no[:30]}          ", end='', flush=True)

    return {
        'Source_File': source_file, 'Page': page_no, 'Bench': bench_name,
        'Day': doc_state.get('day', ''), 'Date': doc_state.get('date', ''),
        'Month': doc_state.get('month', ''), 'Year': doc_state.get('year', ''),
        'Court_No': court_no, 'Judges': doc_state.get('judges', ''),
        'Case_Category': case_cat, 'Section': section,
        'Sr_No': sr_no, 'Case_No': case_no, 'System_ID': sys_id,
        'Case_Title': case_title, 'Petitioner_Advocate': pet_adv,
        'Respondent_Advocates': res_adv,
        'Needs_Review': 'Yes' if needs_review else 'No',
    }


def parse_page(page, page_no, source_file, bench_name, doc_state, global_sr_holder):
    words = page.extract_words(use_text_flow=False, keep_blank_chars=False)
    if not words:
        return []
    raw_lines = cluster_words_into_lines(words)
    data_lines, court_no = classify_and_filter_lines(raw_lines, doc_state)
    if not data_lines:
        return []
    data_words = [w for lw in data_lines for w in lw]
    left_bound, right_bound = detect_column_bounds(data_words)

    lines = []
    for lw in data_lines:
        left, mid, right = bucket_line(lw, left_bound, right_bound)
        lines.append((left, mid, right))

    section = ''
    records = []
    i, n = 0, len(lines)
    while i < n:
        left, mid, right = lines[i]
        if not left and not right and SECTION_RE.match(mid.strip()):
            section = mid.strip()
            i += 1
            continue
        sm = SR_START_RE.match(left)
        if sm and left:
            sr_no = sm.group(1) or sm.group(2) or ''
            block = [(left, mid, right)]
            j = i + 1
            while j < n:
                l2, m2, r2 = lines[j]
                if not l2 and not r2 and SECTION_RE.match(m2.strip()):
                    break
                if SR_START_RE.match(l2) and l2:
                    break
                block.append((l2, m2, r2))
                j += 1
            i = j
            records.append(build_record(block, section, court_no, sr_no, doc_state,
                                         source_file, page_no, bench_name, global_sr_holder))
        else:
            i += 1
    return records


def process_pdf(pdf_path: Path, bench_name, global_sr_holder):
    source_label = pdf_path.name
    all_records = []
    doc_state = {}
    with pdfplumber.open(str(pdf_path)) as pdf:
        for page_no, page in enumerate(pdf.pages, start=1):
            try:
                records = parse_page(page, page_no, source_label, bench_name, doc_state, global_sr_holder)
                all_records.extend(records)
            except Exception as e:
                log.error(f"{source_label} page {page_no}: FAILED ({e}). Skipping page.")
    return all_records


# ----------------------- MAIN -----------------------
def main():
    global_sr_holder = [0]
    all_new_records = []
    session = requests.Session()

    for bench_name, site_cfg in SITES.items():
        if site_cfg["type"] == "case_registry":
            try:
                recs = get_case_registry_records(
                    site_cfg["search_url"], session,
                    site_cfg["caseyear"], site_cfg["casenamecode"],
                    global_sr_holder,
                )
                all_new_records.extend(recs)
                print(f"[{bench_name}] {len(recs)} case records fetched")
            except Exception as e:
                print(f"[{bench_name}] fetch failed: {e}")
            continue

        try:
            if site_cfg["type"] == "json_api":
                links = get_json_api_pdf_links(site_cfg["api_url"], session, max_pages=1)
            elif site_cfg["type"] == "date_form":
                links = get_date_form_pdf_links(site_cfg["form_url"], session,
                                                 lookback_days=site_cfg.get("lookback_days", 3))
            else:
                print(f"[{bench_name}] unknown site type '{site_cfg['type']}' — skipping")
                continue
        except Exception as e:
            print(f"[{bench_name}] fetch failed: {e}")
            continue

        if not links:
            print(f"[{bench_name}] 0 links found")

        is_html_bench = site_cfg["type"] == "date_form" and site_cfg.get("format") == "html_table"

        for url in links:
            try:
                if is_html_bench:
                    resp = session.get(url, headers=HEADERS, timeout=30)
                    resp.raise_for_status()
                    recs = parse_mingora_html(resp.text, url, bench_name, global_sr_holder)
                    all_new_records.extend(recs)
                    print(f"[{bench_name}] {url.split('/')[-2]} -> {len(recs)} records")
                else:
                    pdf_path = download_pdf(url, bench_name)
                    recs = process_pdf(pdf_path, bench_name, global_sr_holder)
                    all_new_records.extend(recs)
                    print(f"\n[{bench_name}] {pdf_path.name} -> {len(recs)} records")
            except Exception as e:
                print(f"[{bench_name}] parse failed for {url}: {e}")

    if not all_new_records:
        print("No new bench records parsed.")
        return

    new_df = pd.DataFrame(all_new_records, columns=FIELDS).astype(str)
    for col in new_df.columns:
        new_df[col] = new_df[col].fillna("")

    if OUTPUT_PARQUET.exists():
        old_df = pd.read_parquet(OUTPUT_PARQUET)
        combined = pd.concat([old_df, new_df], ignore_index=True)
    else:
        combined = new_df

    dedupe_cols = [c for c in ["Bench", "Date", "Court_No", "Sr_No", "Case_No"] if c in combined.columns]
    before = len(combined)
    if dedupe_cols:
        combined = combined.drop_duplicates(subset=dedupe_cols, keep="last").reset_index(drop=True)

    combined.to_parquet(OUTPUT_PARQUET)
    print(f"\nMerged {len(new_df)} bench record(s), dropped {before - len(combined)} duplicate(s). "
          f"Total now {len(combined)} rows -> {OUTPUT_PARQUET.name}")


if __name__ == "__main__":
    main()